---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./repos/weaveworks.yaml
  - ./repos/bitnami.yaml
  - ./repos/prometheus-community.yaml
  - ./repos/matrix.yaml
  - ./repos/multus.yaml
  - ./repos/immich.yaml