apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:SBOuj9t4+s3sHjjDgzyQRQsc8A0NW9Dkl8KRSPkvpf8S736cF1AqAA==,iv:CBWhcdFhrEuxCHdbJDC/3sF6ptAVKHZ/9RMKpzUaWp4=,tag:/Gkyua6uxkKwb/iqKktYvA==,type:str]
sops:
  age:
    - recipient: age1w77q45vfakc48tq3zp35hhdcwxa3zks5vrzwxm9k6ge578zx7gmqkyazy0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MVJYSEVVd2NkSXhJTnFi
        OW1hcVpMbE4rUWtJVTRvem03dHZONkRIMVZZCmcxUlVMN2d2RHFydHllTk5zK3Ji
        REdMbWpGbjdoUHR3MnhLd2ZqQm1Xb3MKLS0tIE9hNkduSVY5Z1FZNTJreWNYVFFK
        Mk5Dc2doWlU5ZnFkRlBXdDBrZnczclkKzOF5peQkU63FDLuW4U1FxwGOYL43rKuw
        G96F87AkKJJudI6TNs2DOucGcRUHTcelMi6qZ9D1acCsPEcx6toQdQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-24T21:49:00Z"
  mac: ENC[AES256_GCM,data:utCqG+3tvUCh0BpUk72lsMnzpzPRRY1rX8jrm+T86iFW336h7W0H8fsECLGY/FqrGGIyzUDleZnB17ZsUjC12FXw04FN71hOoBEY5opS4MS8UDXTV/1IbReEx8dnm6yV3/Co6S0QDU+OWV7W1ySANl8i7n2PSb0iwkFblWHgKuU=,iv:l8gcQX25Z97C03C48ubAffkYuHM+4SwYb10ZCDQzHUA=,tag:O6cNm28oXr0h9F2K4ILixQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
