apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:5zaIaP5QCWV/KXTJ8vjYCgNptQO9b0CvSerjNhaHb/Q=,iv:yXrq5E3Ns6h1Keef1K4xAZxCWNXiKVd+n5zz+q2bURk=,tag:s86PFSu1JvlsjSZOCEqiLw==,type:str]
sops:
  age:
    - recipient: age1w77q45vfakc48tq3zp35hhdcwxa3zks5vrzwxm9k6ge578zx7gmqkyazy0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMmd3S0E2b2dQU3VqNTFt
        cGZNeGUwTlRjTmswY3Q0YmNLTnRrbmxLTFJnCnQwVENoTVpIZ2taUjBoQVRjeDMz
        Q3pyYTlRaEVrT0pueU5MZUZzbUUzd2sKLS0tIDdIN2FkQS9VYjR6Z0pZcGVEYzQy
        bTFMdW5xamMzYkEwTVd3SWNXQU9maGMKIE9WGkOp9t9gzM7bVdRMYCWCyXl5miQP
        U9127IQVFWAPVTzNab06ydeER9YYQ18X5IIK4HN/q+ORVxiVBqogvg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T21:47:42Z"
  mac: ENC[AES256_GCM,data:7cTPPKlgD+Pi9Q1eYU1Ow2e5R4B93GyhCjy36g2dHb6PGHNhyU/YYpqOuLiWwuvjIQrLQBkx18Fa26SvsQ5bB3mtAhO5V65s439gJnVKVIbb/zKjBXBL7+8fw/Vaq/+Z/hnKKIMLZ66NGVeHCREWQgPVm3KsXdAjPvptmnzlMZI=,iv:TMfCdGZYBO1R13eBprSUaG2p+E66676jVKKVaO+qIQY=,tag:MrxmR8kPnSopaACmLFoWmg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
