---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app victoriametrics
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  targetNamespace: observability
  dependsOn:
    - name: longhorn
  path: "./kubernetes/apps/observability/victoria-metrics/app/"
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app victoriametrics-custom
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  targetNamespace: observability
  dependsOn:
    - name: victoriametrics
  path: "./kubernetes/apps/observability/victoria-metrics/custom/"
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret

