---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-configmap
  namespace: media
data:
  DB_PORT: "5432"
  NODE_ENV: "production"
  REDIS_HOSTNAME: "dragonfly.database.svc.cluster.local"
  REDIS_PORT: "6379"
  IMMICH_SERVER_URL: http://immich-server.media.svc.cluster.local:3001
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning.media.svc.cluster.local:3003
  PUBLIC_IMMICH_SERVER_URL: https://photos.${SECRET_DOMAIN}
  UPLOAD_LOCATION: /usr/src/app/upload
  IMMICH_METRICS: "true"