apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: i915
spec:
  spec:
    devices:
      requests:
        - name: intel-gpu-request
          firstAvailable:
          - name: i915
            deviceClassName: gpu.intel.com