---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./i915-gpu-template.yaml
  - ./pvc.yaml
  - ./configmap.yaml
  - ./secret.sops.yaml
  - ./helmrelease.yaml
  - ../../../../templates/gatus/external