apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-upload
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 350Gi
  storageClassName: longhorn-ssd
  volumeName: pvc-0a1ce33a-03e6-4e7a-822c-d09d9d2eb685
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-ml-cache
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn-fast
  volumename: pvc-76474405-207c-49e0-9306-ed6e197e1879
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-thumbnails
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  storageClassName: longhorn-fast
  volumename: pvc-c20f7141-ef6b-46c6-aa69-8729b84be7fe