apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
stringData:
    #ENC[AES256_GCM,data:WQXPxQd9mg==,iv:tkKQxpcRHyO098u1fahspFXFAS9LpuN3HWfrlggtc0c=,tag:Tdctw45pCWTQY4SKj+8rHg==,type:comment]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:kydXNMi5c2Q=,iv:voaKyByH9/nWaTa5/7DjaOXK0gmElq3P0ihpSVmldPw=,tag:Dh3EyLkUDMaiS0dWIfvRYg==,type:str]
    DB_HOSTNAME: ENC[AES256_GCM,data:2y8h63I4IiO8UnaYh5VH9CtIDD4aHaoaEVzTke4t6dZkgLJ0e/JxYg==,iv:58Gw7nerD8ye9H1Ygb40+FR7m3nn3gABfXaZtij5UWw=,tag:JYTjfxUcjh236e9RFNa7CA==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:+Cwb80tgwKhgLfpnu0jEuqXfmWWZ/g==,iv:duxJDcb5c57JZvPWEPI0wm6FpwSN3gWtQ4xGgfPxNto=,tag:qWEgxR2PlePbe185Tl40mA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:R0UVifsTjJyFBczMg1gzXf9RzCOmmw==,iv:dGQZkmipImBBKmwRO/a0YEbELwSgH55EY+pylB259vQ=,tag:RpCNSxnnZl5DklXeLnBJbA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:vKv5ZMel2Lo0q+N6rhvkxnnjsVI=,iv:jpZepbdpvwPJsk/Tu0zHpY7QrBR4aNAlIQZ/SwHV8rc=,tag:gfaoE/9u76LavWjghOpAiw==,type:str]
    #ENC[AES256_GCM,data:P5fPMwCsr+VQTvPb6C4=,iv:l/BCpopvfXKMALnayafjeBqtWDQXtI4luAUyhA8ZW8M=,tag:7acsj0qG9LXY2t/JXfPOeA==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:lb/8o6WqkAo=,iv:blSoplIBSi6My3hFrD5t24+f1sXOVSGcAiQueKgqFus=,tag:/JW1MihJB/mS28EQU0JlRA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:Poh9XdFm5AMz8LWiWEgHk8TfD9kjsRw8BXoVqtFPLikAORl4SpSruw==,iv:h5/ijgH7v7hK1iDOo+pqvedCOCDG2zDQG5vh1vkArx4=,tag:WPBLARwE9Lu2YAo1p6nbJg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:06+aAvUyZS65IA==,iv:q/SJV6eTDQEQKzTn7hKW8O0eRof3CXQhUnctQUQlRv4=,tag:PgP653vJ/zZUQhS85DtAvg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:wpJDcU1AGYtnD8NuZZkEBQI=,iv:nMbIqV3gfunXhBHNUyzuA+Q6/PKwh5Dry4RVBcuC+DE=,tag:CW0IA3pLUjd4MchiRhz7Jg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:Rnp6jBbtzWZUwFElN5S3NN+ewHMNlQ==,iv:1g1iBskuyiseJFYAnHHG50XtZIUaTKpc534NHHlavas=,tag:okT1zoVUUbKPjZI40Uyzkw==,type:str]
sops:
    age:
        - recipient: age1w77q45vfakc48tq3zp35hhdcwxa3zks5vrzwxm9k6ge578zx7gmqkyazy0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3YS8xaVRRblc2VnNOSlBi
            N3JYaEI4OTBSWldxVmd5WEtGT1BaZTE1eTBNCndaWmFheHNXSDZqT29FbForRCtm
            MGgxTE9iNmlzZzZtcDRieVg1WnNuNjAKLS0tIE82M2JHdlVuSUgvNG5wWHd1cW13
            ZkY0Y0s3QVdOMUdRSGlNYUw5aGZIN0kKdTV9jHCG50EdmSpYGP1rm+QbeFvHdoy3
            VxQoWzHGM2m1CJp+5+0LWJlqYJuqIhyLJzARQV4wgatF+OrMWzfcAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T15:02:38Z"
    mac: ENC[AES256_GCM,data:pr4vjdRmPxNqgZKrxz+XzPU9BgmaeQJvlxIUGGXKLzRNSO1blJOpLTD2QJRA8xxcDdKykm1fz0HjmTYvrMhF4vXpdFOr3r3+RS226Jc06casjSyVc7B8d/SLjGe+ez43yRU3KT7EyevCEMprzFlRnwwbTs1SmrU7rldbWIw75vE=,iv:RPtHhAvbZvG7sEsWNNuSopruaDSHatGFrZyKFw3U+nM=,tag:Tg9bgW8t8/YN3gd2eUkp6w==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
