apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:9O6slNpXsnBVx/aSjw0GruSVzaNKMDGJj+dHZxT6MJmd8l+Xk6TQksax+OSt623Gw0LrYnwTjonfnoso7OpYuWs2GwtirGOTmZyKkkz2SUOK63wY+Tq9f4b31/x71/33liqLrkF+qZkvwPsifHNdZBOnGFhYNR+JXiubUU6qeKVGgUt62M0HGNe93wjBtlQd5YfQct1pZ5yUiiUeRWqBV7JAfXfbiZashJl06TGbmo3sTEQ5,iv:MP96mhGAM7+q96l8ygHh7FKzGkkWGRAz+v2AFyv8WLY=,tag:qAfOfv3gxwSr4aSsagX8yg==,type:str]
sops:
  age:
    - recipient: age1w77q45vfakc48tq3zp35hhdcwxa3zks5vrzwxm9k6ge578zx7gmqkyazy0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMWJoUkpsditzVyttWnZk
        WUg2VVJFUHVzREl3VHRsb3JraW5CUjhpZlEwCjVESlh5TXRtWngvQVZ3ZEdyWHVw
        VDlpM2tLTWpxVmFRQlZndjFWcjNONFkKLS0tIG5yNEcweXVTbG1yZ05OMTdhQ3E1
        WWk2MUttRFZsSFlPZ0dHeDJNRjFzcm8K0Q5qusiCRfTSnT18DwzVl7S4saphzj7n
        K/2QvyyyXR7F+Hyyx19MYLIr4J6QyT4DbdtssdNnwdKWP70y/qqWDQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-24T21:49:00Z"
  mac: ENC[AES256_GCM,data:5fwdYZ0dhJPLQ/mzrMRWxDMQavWPNf5AR8DJda2efM4mO3qIBQAroiXTYbW6t0AeZN1bc1npDs9Llzz/0z8Dd3Fr4mD0ah5EsuQt3TDpTjVuJxXySFUmUpjLFTSDfBXl+8QKHAVrgDa6nzMyLEwVAgAF31TjLhjc+VhdTKWwXB0=,iv:PGi7ioLrQ8FxM45ThVCcUBzFZHlq78/kJLnx+XlGNBs=,tag:E6hs/iPO5CeJR2zESBkWnA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
