helmDefaults:
  cleanupOnFail: true
  wait: true
  waitForJobs: true

releases:
  - name: flux-operator
    namespace: flux-system
    chart: oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator
    version: 0.33.0
    values: ['flux-operator/values.yaml']

  - name: flux-instance
    namespace: flux-system
    chart: oci://ghcr.io/controlplaneio-fluxcd/charts/flux-instance
    version: 0.33.0
    values: ['flux-instance/values.yaml']
    needs: ['flux-system/flux-operator']