---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../flux/components/namespace

resources:
  - ./namespace.yaml
  - ./external/ks.yaml
  - ./internal/ks.yaml
  - ./multus/ks.yaml
  - ./envoy-gateway/ks.yaml
  - ./cloudflare-dns/ks.yaml
